### ISSUE TITLE
Permission node for the command

### ISSUE THREAD

**Issue by acidbyt3** [mickedplay/ChatLog#1]
Currently there doesn't seem to be a permission node to restrict the /chatlog command usage.

Any chance you could add one? :)

**Comment by mickedplay** [comment]
Yeah i know there aren't any permissions yet.

Sorry, but currently I'm working on other projects, but I hope to release an update till october. I can not say for sure whether rights are already implemented then. Maybe it's just a bugfix of other problems but I try to get more time on projects like these.

**Comment by acidbyt3** [comment]
That's fine, thank you for the quick reply! :)
